// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription
=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For details, see link:#_planning_the_deployment[Planning the deployment] earlier in this guide.
. Make sure that your AWS account is configured correctly, as discussed in the link:#_technical_requirements[Technical requirements] section.

// Optional based on Marketplace listing. Not to be edited
ifdef::marketplace_subscription[]
=== Subscribe to one or more {partner-product-name} AMIs

This Quick Start requires a subscription to one or more AMIs available in AWS Marketplace. See the link:#_software_licenses[Software licenses] section of this guide.

. Sign in to your AWS account.
. For each AMI you will subscribe to, open the page for the AMI in AWS Marketplace and choose *Continue to Subscribe*.
. Review the terms and conditions for software usage, and then choose *Accept Terms*. +
  A confirmation page loads, and an email confirmation is sent to the account owner. For detailed subscription instructions, see the https://aws.amazon.com/marketplace/help/200799470[Getting started^] page in the AWS Marketplace Buyer Guide.

. When the subscription process is complete, exit out of AWS Marketplace without further action. *Do not* provision the software from AWS Marketplace—the Quick Start deploys the AMI for you.

If your deployment will contain BYOL instances:

.	Navigate to the GitHub repository for the Quick Start and download the repository.
.	Unzip the file on your local machine.
.	Create an S3 bucket for your deployment. The name of the S3 bucket is used for the parameter *Quick Start S3 bucket name* (`QSS3BucketName`). This name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-). 
.	Inside this directory, create another directory to store the deployment resources. The name of this directory is used for the parameter *Quick Start S3 key prefix* (`QSS3KeyPrefix`). The S3 key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
.	Navigate to this second directory and upload the files and directories you extracted in step 2 to this location.
.	Navigate to the assets directory, create a directory named `fgt-asg-license`, and upload your FortiGate license files to this directory.


endif::marketplace_subscription[]
// \Not to be edited

=== Launch the Quick Start

WARNING: If you’re deploying {partner-product-name} into an existing VPC, make sure that your VPC has two private subnets in different Availability Zones for the workload instances and that the subnets aren’t shared. This Quick Start doesn’t support https://docs.aws.amazon.com/vpc/latest/userguide/vpc-sharing.html[shared subnets^]. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[NAT gateways^] in their route tables to allow the instances to download packages and software without exposing them to the internet. Also make sure that the domain name option in the DHCP options is configured as explained in http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[DHCP options sets^]. You provide your VPC settings when you launch the Quick Start.

NOTE: You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service used by this Quick Start. Prices are subject to change.

Each deployment takes about {deployment_time} to complete.

. Sign in to your AWS account, and choose one of the following options to launch the AWS CloudFormation template. For help with choosing an option, see link:#_deployment_options[Deployment options] earlier in this guide.

[cols="60,40a"]
|===
^|https://fwd.aws/zkV8P[Deploy {partner-product-name} into a new VPC on AWS^] 
^|https://fwd.aws/6nDP6[View template^]
^|https://fwd.aws/gwdmk[Deploy {partner-product-name} into an existing VPC on AWS^] 
^|https://fwd.aws/xw5QN[View template^]
|===

[start=2]
. Check the AWS Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for {partner-product-name} will be built. The template is launched in the {default_deployment_region} Region by default.

// *Note:* This deployment includes Amazon EFS, which isn’t currently supported in all AWS Regions. For a current list of supported Regions, see the https://docs.aws.amazon.com/general/latest/gr/elasticfilesystem.html[endpoints and quotas webpage].

[start=3]
. On the *Create stack* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. For details on each parameter, see the link:#_parameter_reference[Parameter reference] section of this guide. When you finish reviewing and customizing the parameters, choose *Next*.