---
AWSTemplateFormatVersion: 2010-09-09
Description: Deploys and configures FortiGates to the selected subnets in a VPC (qs-1s1rf57s6)
Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), periods (.) and forward slash (/).
    Default: quickstart-fortinet-fortigate/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), periods (.) and
      forward slash (/).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: Region where the Quick Start S3 bucket (QSS3BucketName) is
      hosted. When using your own bucket, you must specify this value.
    Type: String
  CustomIdentifier:
    Type: String
    MaxLength: '10'
    AllowedPattern: '[A-Za-z0-9]+'
    ConstraintDescription: must only contain uppercase and lowercase letters and numbers
    Description: >-
      An identifier as resource name prefix. Must be at most 10 characters long
      and only contain uppercase, lowercase letters, and numbers.
  VPCID:
    Type: 'AWS::EC2::VPC::Id'
    Description: >-
      Enter a valid VPC ID to deploy. The VPC must have the option 'DNS
      hostnames' enabled.
  VPCCIDR:
    Type: String
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]){1}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
    ConstraintDescription: must be a valid CIDR block format.
    Description: >-
      The CIDR block for the VPC where the FortiGate NAT Gateway will be
      deployed.
  SubnetId1:
    Type: 'AWS::EC2::Subnet::Id'
    Description: 'The subnet ID for the primary network interface of the NAT Gateway #1.'
  SubnetId2:
    Type: 'AWS::EC2::Subnet::Id'
    Description: 'The subnet ID for the secondary network interface of the NAT Gateway #1.'
  SubnetId3:
    Type: 'AWS::EC2::Subnet::Id'
    Description: 'The subnet ID for the primary network interface of the NAT Gateway #2.'
  SubnetId4:
    Type: 'AWS::EC2::Subnet::Id'
    Description: 'The subnet ID for the secondary network interface of the NAT Gateway #2.'
  FortiGateImageId:
    Type: String
    Description: FortiGate Official AMI ID.
  FortiGateInstanceType:
    Type: String
    Description: Instance Type.
  FortiGateAdminCIDR:
    Type: String
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5]){1}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
    ConstraintDescription: must be a valid CIDR block format and 0.0.0.0/0 is not recommended.
    MinLength: 9
    Description: >-
      CIDR block for external admin management access. **WARNING!** The default
      value 0.0.0.0/0 accepts connections from any IP address. Please consider
      hanging it to match your needs.
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: Amazon EC2 Key Pair for admin access.
  FortiGateAdminPort:
    Type: Number
    MinValue: 1
    MaxValue: 65535
    ConstraintDescription: must be a valid port number between 1 and 65535.
    Description: >-
      A port number for FortiGate administration. Default to 8443. Do not use:
      443, 541, 514, 703.
  FortiAnalyzerIp:
    Type: String
    Description: The IP of FortiAnalyzer to send logs to.
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  sgFortiGateInstance:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: FortiGate instance base security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: !Ref FortiGateAdminCIDR
          FromPort: 22
          ToPort: 22
        - IpProtocol: tcp
          CidrIp: !Ref FortiGateAdminCIDR
          FromPort: !Ref FortiGateAdminPort
          ToPort: !Ref FortiGateAdminPort
        - IpProtocol: '-1'
          CidrIp: !Ref VPCCIDR
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPCID
  IamRoleFgtInstance:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AmazonS3ReadOnlyAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSLambdaExecute
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - 's3:GetObject'
                Resource: !Sub
                  - arn:${AWS::Partition}:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*
                  - QSS3BucketName: !Ref QSS3BucketName
                    QSS3KeyPrefix: !Ref QSS3KeyPrefix
                Effect: Allow
          PolicyName: fortigate-autoscale-s3-access-policy
  IamInstanceProfileFgt:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref IamRoleFgtInstance
  StackCreateFortiGateInstance1:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        CustomTagValue: !Ref CustomIdentifier
        FortiGateInstanceType: !Ref FortiGateInstanceType
        KeyPairName: !Ref KeyPairName
        FortiGateAdminPort: !Ref FortiGateAdminPort
        FortiGateSecurityGroupId: !Ref sgFortiGateInstance
        SubnetIdA: !Ref SubnetId1
        SubnetIdB: !Ref SubnetId2
        FortiGateImageId: !Ref FortiGateImageId
        InstanceProfile: !Ref IamInstanceProfileFgt
        FortiAnalyzerIp: !Ref FortiAnalyzerIp
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/create-fortigate.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      TimeoutInMinutes: 10
  StackCreateFortiGateInstance2:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        CustomTagValue: !Ref CustomIdentifier
        FortiGateInstanceType: !Ref FortiGateInstanceType
        KeyPairName: !Ref KeyPairName
        FortiGateAdminPort: !Ref FortiGateAdminPort
        FortiGateSecurityGroupId: !Ref sgFortiGateInstance
        SubnetIdA: !Ref SubnetId3
        SubnetIdB: !Ref SubnetId4
        FortiGateImageId: !Ref FortiGateImageId
        InstanceProfile: !Ref IamInstanceProfileFgt
        FortiAnalyzerIp: !Ref FortiAnalyzerIp
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/create-fortigate.template.yaml'
        - S3Region: !If [ UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion ]
          S3Bucket: !If [ UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName ]
      TimeoutInMinutes: 5
Outputs:
  InstanceId1:
    Description: 'The instance ID of the FortiGate NAT Gateway #1.'
    Value: !GetAtt
      - StackCreateFortiGateInstance1
      - Outputs.
  InstanceId1PublicIp:
    Description: 'The public IP address of the FortiGate NAT Gateway #1.'
    Value: !GetAtt
      - StackCreateFortiGateInstance1
      - Outputs.PublicIP
  InstanceId1PrivateIp:
    Description: 'The nic0 private IP address of the FortiGate NAT Gateway #1.'
    Value: !GetAtt
      - StackCreateFortiGateInstance1
      - Outputs.Nic0PrivateIp
  InstanceId1Nic1Id:
    Description: 'The nic1 ID of the FortiGate NAT Gateway #1.'
    Value: !GetAtt
      - StackCreateFortiGateInstance1
      - Outputs.NetworkInterface1Id
  InstanceId1Nic1PrivateIp:
    Description: 'The nic1 private IP address of the FortiGate NAT Gateway #1.'
    Value: !GetAtt
      - StackCreateFortiGateInstance1
      - Outputs.Nic1PrivateIp
  InstanceId2:
    Description: 'The instance ID of the FortiGate NAT Gateway #2.'
    Value: !GetAtt
      - StackCreateFortiGateInstance2
      - Outputs.InstanceID
  InstanceId2PublicIp:
    Description: 'The public IP address of the FortiGate NAT Gateway #2.'
    Value: !GetAtt
      - StackCreateFortiGateInstance2
      - Outputs.PublicIP
  InstanceId2PrivateIp:
    Description: 'The nic0 private IP address of the FortiGate NAT Gateway #2.'
    Value: !GetAtt
      - StackCreateFortiGateInstance2
      - Outputs.Nic0PrivateIp
  InstanceId2Nic1Id:
    Description: 'The nic1 ID of the FortiGate NAT Gateway #2.'
    Value: !GetAtt
      - StackCreateFortiGateInstance2
      - Outputs.NetworkInterface1Id
  InstanceId2Nic1PrivateIp:
    Description: 'The nic1 private IP address of the FortiGate NAT Gateway #2.'
    Value: !GetAtt
      - StackCreateFortiGateInstance2
      - Outputs.Nic1PrivateIp
